# ?????? ?? ?? ...

# OpenWeather API ??  <- ??
weather.url=http://api.openweathermap.org/data/2.5/weather
weather.api_key=c986793c4e7bfa286b3b007b5ba6940e
weather.icon_url=http://openweathermap.org/img/w/%s.png
